mode: auto

silent: false

commentMessage: 'Branch ${branchName} created for issue: ${issue.number}-${issue.title}'

defaultBranch: 'develop'

branchName: 'issue-${issue.number}/${issue.title,}'

gitSafeReplacementChar: '-'

branches:
  - label: [ feature ]
    prefix: feature/

  - label: [ bug ]
    prefix: bugfix/
  
  - label: [ documentation ]
    prefix: documentation/

  - label: [ testing ]
    prefix: testing/

  - label: '*'
    prefix: issues/

  - label: 
      - 'major'
      - 'minor'
      - 'patch'
    name: develop
    prTarget: master

openPR: true
autoCloseIssue: true

copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: false
copyIssueMilestoneToPR: false
