mode: auto

silent: true

defaultBranch: 'develop'

branchName: 'issue-${issue.number}/${issue.title,}'

gitSafeReplacementChar: '-'

branches:
  - label: [ feature ]
    prefix: feature/

  - label: [ bug ]
    prefix: bugfix/

  - label: [ documentation ]
    prefix: documentation/

  - label: '*'
    prefix: issues/

  - label: no-branch
    skip: true

commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'

openPR: true
autoCloseIssue: true

copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: false
copyIssueMilestoneToPR: false
