name: Manual Images

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        required: true
        default: 'workflows'
        type: choice
        options:
          - workflows
          - master
  
jobs:
  backend:
    name: Manual backend build

    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.BRANCH }}