name: Publish package to GitHub Packages
on:
  release:
    types: [ released ]

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      
      - name: Checkout the code   
        uses: actions/checkout@v3

      - name: Setup java SDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build application
        run: mvn clean install

      - name: Find file
        run: |
          cd ./target & ls & cd ./target & ls

      - name: Upload binaries to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./target/*.jar"
          update_latest_release: true
          overwrite: true
          tags: true
          draft: true

      - name: Publish package
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}