name: PR Labeler
on:
  pull_request:
    types: [opened, reopened, synchronize, assigned]
    branches: 
      - develop
      - workflows
      - '*/*'

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write 
    runs-on: ubuntu-latest
    steps:
      - name: Add labels to PR
        uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}