name: Publish

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./target/my-app-1.0.jar
        asset_name: my-app-1.0
        tag: ${{ github.ref }}
        overwrite: true