name: Release Drafter

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
  
permissions:
  contents: read

jobs:
  - name: Upload To Github Release
    uses: xresloader/upload-to-github-release@v1.3.9
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      file: "*.jar"
      overwrite: true
      draft: true

