name: Test release version

on:
  release:
    types: [ released ]

env:
  VERSION: ${{  github.ref_name }}

jobs:
  test_version:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: GitHub Tag Name example
        env:
          VERSION_TAG: $VERSION
        run: |
            echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
            echo "Tag name from github.ref_name: $VERSION_TAG"
