name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize, assigned]
    branches:
      - '!workflows'
      - master

jobs:
  update_version:
    runs-on: ubuntu-latest 

    if: contains(github.event.pull_request.labels.*.name, 'run-tests')

    steps:
    - uses: actions/checkout@v3

    - name: Update POM Version
      run: |
        echo "Updating to version: $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)"
        mvn versions:set -DnewVersion=$(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)

    - name: Diff check
      run: git diff

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: '.'
        default_author: github_actions
        push: origin HEAD:develop --force
