name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  get_milestone:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3

    - name: Update POM Version
      run: |
        echo "Updating to version: $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)"
        mvn versions:set -DnewVersion=$(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)

    - name: Commit
        run: |
          git config --local user.email "joaopcatalao@gmail.com"
          git config --local user.name "Github Actions"
          git add .
          git commit -m "Updated Version" -a