name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    labels: 
      - new-version

jobs:
  get_milestone:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Get milestone
      id: get_milestone
      run: |
        echo $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)

    - name: Update version
      run: ./bin/mac/updateversion.sh
        