name: Publish package to GitHub Packages
on:
  push:
    branches: master
    labels: 
      - new-version

jobs:
  update:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print milestone
        run: echo ${{ github.milestone }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}