name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    labels: 
      - new-version

jobs:
  get_milestone:
    runs-on: ubuntu-latest 

    steps:
    - name: Get milestone
      id: get_milestone
      run: |
        echo '.pull_request.milestone.title'
    - name: Use milestone
      run: |
        echo "Milestone: $MILESTONE_NAME"