name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    labels: 
      - new-version

jobs:
  get_milestone:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2

    - name: Update POM Version
      env:
        new_version: $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)
      run: |
        echo "Updating to version: ${new_version}"
        mvn versions:set -DnewVersion=$(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)

    - name: Commit version
      run: git commit -am "Update POM version to 1.0.${{ env.BUILD_NUMBER }}"

    - name: Push changes
      run: git push