name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    labels: 
      - new-version

jobs:
  get_milestone:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2

    - name: Update POM Version
      run: mvn versions:set -DnewVersion=$(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)

    - name: Commit changes
      run: git config --local user.email "action@github.com" && git config --local user.name "GitHub Action" && git commit -am "Update POM version to ${INPUT_VERSION}"
        