name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - master
    labels: 
      - new-version

jobs:
  update:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check milestone
        uses: actions/github-script@v5
        with:
          script: |
            const { data } = await github.request("GET /repos/{owner}/{repo}/pulls/{pr}", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pr: context.payload.pull_request.number
            });
            if (data.milestone) {
              core.info(`This pull request has a milestone set: ${data.milestone.title}`);
            } else {
              core.setFailed(`A maintainer needs to set the milestone for this pull request.`);
            }

      - name: Print milestone
        shell: bash
        env:
          milestone: milestone
        run: print $milestones