name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    labels: 
      - new-version

jobs:
  get_milestone:
    runs-on: ubuntu-latest 

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get milestone
      id: get_milestone
      run: |
        echo $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)
    
    - name: Update version
      shell: bash
      run: ./bin/mac/updateversion.sh $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)
        