name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - master
    labels: 
      - new-version

jobs:
  update:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print milestone
        run: ./bin/mac/updateversion.sh ${{ github.milestone }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}