name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - master
    labels: 
      - new-version

jobs:
  update:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get milestone information
        run: |
          curl -H "Authorization: token ${{ secrets.PROJECT_WORKFLOW_SECRET }}" https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/milestones > milestones.json

      - name: Set Milestone
        run: |
          milestone_name=$(jq -r '.[0].title' milestones.json)
          echo "Milestone: ${milestone_name}"
          env.MILESTONE_NAME = ${milestone_name}