name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    labels: 
      - new-version

jobs:
  get_milestone:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get Milestone
        id: get_milestone
        uses: actions/github@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: pull ${{ github.event.number }}
    
      - name: Get Milestone
        run: echo "Milestone name: ${{ steps.get_milestone.outputs.milestone }}"