name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_version:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3

    - name: Update POM Version
      run: |
        echo "Updating to version: $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)"
        mvn versions:set -DnewVersion=$(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)

    - name: Commit changes
      run: |
        git config --local user.email "joaopcatalao@gmail.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Updating to version: $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)"
        git push origin main