name: Update POM files version

on:
  pull_request:
    types: [opened, reopened, synchronize]
    labels: 
      - new-version

jobs:
  get_milestone:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2

    - name: Update POM Version
      run: |
        echo "Updating to version: $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)"
        mvn versions:set -DnewVersion=$(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)

    - name: Setup github account
      run: |
        git config --global user.email "joaopcatalao@gmail.com"
        git config --global user.name "Joao Catalao"

    - name: Commit version
      run: git commit -am "Update POM version to $(jq -r '.pull_request.milestone.title' $GITHUB_EVENT_PATH)"
      
    - name: Push changes
      run: git push